# Generated by Django 4.0.1 on 2023-01-23 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_purchaserequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='approval',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='cr',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='date',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='value',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='value_currency',
        ),
    ]
